### PR TITLE
Add frontend resource yaml

### PR DESCRIPTION
**Pull request by adamrdrew**
This patch adds the frontend resource YAML for the new frontend build process.

### CODE REVIEW

**Comment by adamrdrew** [comment]
I don't think the failures are due to this change. I just added a YAML file for ci/cd. Can we get this merged even if your tests are failing?

**Comment by gkarat** [comment]
This must be one of our flaky component tests. Re-running the job

**Review by gkarat — APPROVED** [review]
LGTM! Compared with the existing config example for RHEL Advisor and also checked if cloud-services-config info fits with this PR (e.g., like navItems, etc.), didn't find any issues, thanks

**Pull request merged**
