### PR TITLE
feat(OCPADVISOR-138): workloads table empty state

### PR DESCRIPTION
**Pull request by AsToNlele**
[OCPADVISOR-138](https://issues.redhat.com/browse/OCPADVISOR-138)

### No workload recommendations:
When you recieve an empty array of workloads
[Mock](https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/ZVg3O2J)

image

#### How to test:
in `src/Components/WorkloadsListTable/index.js`
replace query with
```js
  const query = {
    data: { workloads: [] },
    isSuccess: true,
    isError: false,
  };
```

### Workloads data unavailable
When request returns 404
[Mock](https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/zyQgxvy)

image

#### How to test:
in `src/Components/WorkloadsListTable/index.js`
replace query with
```js
  const query = {
    data: { workloads: [] },
    isSuccess: false,
    isError: true,
    error: { status: 404 },
  };
```

### CODE REVIEW

**Review by johnsonm325 — CHANGES_REQUESTED** [review]
Based on the mocks, the top of the page should be updated to `Advisor workloads`.

https://github.com/RedHatInsights/ocp-advisor-frontend/blob/master/src/Components/WorkloadsList/index.js#L25

**Comment by AsToNlele** [comment]
> Based on the mocks, the top of the page should be updated to `Advisor workloads`.
> 

Sorry, there was a discussion about the title, and it was changed to "Workloads"

**Review by Fewwy — APPROVED** [review]
LGTM

**Pull request merged**
