### PR TITLE
fix(Risk of change): Change risk of change text

### PR DESCRIPTION
**Pull request by gkarat**
Implements https://issues.redhat.com/browse/OCPADVISOR-69.

This changes the description of different levels of risk of change.

### CODE REVIEW

**Comment by leSamo** [comment]
Why was the text taken out of intl? Was this intentional soft deprecation or mistake?

**Comment by gkarat** [comment]
@leSamo, yeah, I decided not to mess with it just because I needed to include ol, li tags. Given we want to deprecate it, I took a shortcut 😛

**Review by leSamo — APPROVED** [review]
Fair enough :D

**Pull request merged**
