### PR TITLE
chore(RHINENG-8334): hide severity column until backend is ready

### PR DESCRIPTION
**Pull request by Fewwy**
https://issues.redhat.com/browse/RHINENG-8334

image

### CODE REVIEW

**Review by gkarat — COMMENTED** [review]
Looks like sorting by Objects is now broken

https://github.com/RedHatInsights/ocp-advisor-frontend/assets/31385370/23e16a1b-c3e4-4b43-a21b-1aa6cdda5771

**Comment by AsToNlele** [comment]
Good catch @gkarat! Fixed

**Review by gkarat — APPROVED** [review]
lgtm! thanks folks!

**Pull request merged**
